### ISSUE TITLE
Add Locust version in docker image tag

### ISSUE THREAD

**Issue by dogzzdogzz** [peter-evans/locust-docker#43]
Could you add Locust version in docker image tag so we can know if we need to update docker image for newer locust version ? Thanks.

**Comment by peter-evans** [comment]
Hi @dogzzdogzz 

Please could you explain a bit more what you mean? Are you suggesting that as well as the current tags you would like the images tagged with an additional tag that follows the version of locust?

For example, the current release has the tags `1.6.1`, `1.6` and `latest`. You would like to see another tag like `locustio-0.14.4`? This would be similar to latest, because future versions of this Docker image that don't update the `locustio` dependency would overwrite the tag and you would be automatically pulling the new version of the image. Is that your intention?

**Comment by dogzzdogzz** [comment]
Specifying locust version in tag,  could be like this:
- ```1.6.1-locustio0.14.4```
- ```latest-locustio0.14.4```

So we can know the locust version explicitly from the docker image tag without tracing back to github source code.

Ref: https://hub.docker.com/_/node/

**Comment by peter-evans** [comment]
That makes sense and seems to follow the same publishing standard as many popular images, such as node. I will work on adding these tags in addition to the current ones to maintain backwards compatibility.

**Comment by peter-evans** [comment]
These tags are added for the latest release. Subsequent releases will follow the same pattern.

- `1.6.2`
- `1.6`
- `latest`
- `1.6.2-locustio0.14.4`
- `1.6-locustio0.14.4`
- `latest-locustio0.14.4`

Thank you for suggesting this!
